'use strict';
// Launch planning is a view of evidence and monitoring, never a booking or invoice gate.
const areas=[
 {id:'launch:journey',group:'action',title:'Complete one booking and payment journey',owner:'Office, with a participant and worker',why:'Confirm that the right people receive the right information and payment updates.',steps:['On this website, follow a booking through shift completion and its review or query options.','Check the invoice amount, secure payment link, confirmed payment balance and receipt.','Confirm that the participant or authorised helper receives the actual emails and action alerts.'],links:[['Open bookings','#/admin/bookings'],['Open payment tracking','#/payment-tracking?tab=invoices']],findings:['A11','A12','A13','A14','A15','A30','A33']},
 {id:'launch:care',group:'action',title:'Confirm your care and business arrangements',owner:'Business owner and care lead; adviser where needed',why:'Match the website to the services, people and arrangements your business actually provides.',steps:['Confirm the business details, service scope, applicable registration evidence and public claims. Reuse current records.','Check worker eligibility, participant consent and agreements for the services being offered.','Confirm who handles incidents, complaints, excluded supports and urgent contact. Record any specialist advice needed.'],links:[['Open verification','#/admin/verification'],['Open policies and documents','#/admin/documents?section=pages']],findings:['A04','A05','A08','A20','A28','A29','A34','A36']},
 {id:'launch:usability',group:'action',title:'Try the essential tasks on a phone',owner:'Office, with a participant and worker',why:'Find confusing screens or inaccessible controls before people depend on them.',steps:['Ask a participant and worker to try registration, booking, notes, review and invoice access on their own devices.','Try keyboard navigation, enlarged text and any assistive technology they use.','Record important barriers, who will fix them and the result when tried again. A larger research study can follow later.'],links:[['Open participant records','#/admin/compliance?section=participants'],['Open bookings','#/admin/bookings']],findings:['A17','A18','A19','A26','A27','A31','A32','A35','A43']},
 {id:'launch:privacy',group:'specialist',title:'Check access, privacy and sign-in',owner:'Technical support and privacy adviser',why:'Protect personal records and make account recovery dependable.',steps:['Confirm that participants, helpers and workers can access only the records allowed for their role and relationship.','Check administrator sign-in and recovery on the deployed website, using separate named accounts.','Confirm actual data handling, retention and provider arrangements. Include independent security review evidence; assess optional AI only if it will be used.'],links:[['Open website alerts','#/admin/assurance?tab=operations'],['Open people','#/admin/people']],findings:['A01','A02','A03','A06','A21','A22','A23','A37']},
 {id:'launch:pay',group:'specialist',title:'Confirm charges and worker pay',owner:'Finance or payroll adviser, with the office',why:'Charge the agreed amount and keep worker payroll accurate and separate from customer payments.',steps:['Check ordinary, weekend, public-holiday, active overnight and sleepover examples against the services and agreements you use.','Confirm the payroll method, actual employment or contractor arrangements, pay cycle and entitlements.','Check how payroll results, refunds and provider payouts are reconciled. An invoice marked paid does not transfer wages.'],links:[['Open payment tracking','#/payment-tracking?tab=invoices'],['Open worker pay','#/journey?panel=payroll']],findings:['A09','A10','A25']},
 {id:'launch:recovery',group:'specialist',title:'Prove recovery and failure alerts',owner:'Technical support or hosting provider',why:'Recover records and respond promptly if the website or a connected service fails.',steps:['Restore a copy of a backup into an isolated temporary location and confirm records and uploaded files. Do not overwrite this website.','Confirm the off-instance backup and who receives failure alerts. Test the agreed recovery procedure.','Check the deployed runtime, expected launch capacity and recovery from email or payment-service failures.'],links:[['Open website alerts','#/admin/assurance?tab=operations'],['Open system checks','#/admin/settings?section=checks']],findings:['A07','A16','A24','A38','A44']}
];
const later=['A39','A40','A41','A42'];
function reviewState(review,today){
 if(!review)return {state:'unrecorded',label:'Check not yet recorded',tone:'action'};
 if(review.review_due&&review.review_due<today)return {state:'due',label:'Review date reached',tone:'action'};
 if(review.decision==='approved')return {state:'recorded',label:'Evidence recorded',tone:'complete'};
 if(review.decision==='not-applicable')return {state:'not-applicable',label:'Not applicable — reason recorded',tone:'neutral'};
 return {state:'needs-work',label:'Follow-up needed',tone:'action'};
}
function summary({actions,latest,today,operations,certificate,holidays}){
 const alertCheck=(id,title,prefix,detail)=>{const alerts=operations.filter(x=>x.key===prefix||x.key.startsWith(prefix+':'));return {id,title,state:alerts.length?'action':'clear',tone:alerts.length?'action':'complete',label:alerts.length?`${alerts.length} ${alerts.length===1?'alert':'alerts'} to check`:'No current alerts',detail,alerts:alerts.map(x=>({key:x.key,title:x.title,detail:x.detail})),href:'#/admin/assurance?tab=operations'};};
 return {
  areas:areas.map(a=>{const review=latest(a.id)||null;return {...a,review,...reviewState(review,today)};}),
  automatic:[
   {id:'certificate',title:'Website certificate',state:certificate?.state||'pending',tone:certificate?.tone||'waiting',label:certificate?.label||'Automatic check scheduled',checked_at:certificate?.checked_at||null,detail:'The website checks its certificate automatically and retries temporary failures. Hosting handles renewal.',href:'#/admin/assurance?tab=operations'},
   alertCheck('storage','File storage','storage','Checks that file storage is writable and has enough free space. Actual uploaded-file recovery is checked separately.'),
   alertCheck('backup','Recent backup','backup','Checks for a recent complete local backup. A successful restore and an off-instance copy still need evidence.'),
   alertCheck('jobs','Background processing','job','Shows scheduled jobs that failed or are overdue. This does not confirm a complete customer journey.'),
   alertCheck('delivery','Message delivery alerts','mail','Flags known delivery failures and ageing messages. No current alerts does not confirm arrival in a real inbox.'),
   {id:'holidays',title:'Holiday rate lookup',state:'automatic',tone:'waiting',label:'Automatic lookup enabled',checked_at:holidays?.checked_at||null,detail:'NSW dates refresh automatically with a saved fallback. No holiday sign-off is needed. Confirm the service location and agreed charges.',href:'#/admin/settings?section=pay'}
  ],
  later:actions.filter(a=>later.includes(a.id)),
  total_areas:areas.length,
  audit_count:actions.length
 };
}
module.exports={areas,later,reviewState,summary};
