#!/usr/bin/env node
'use strict';
/* BookIt — generate docs/api-route-inventory.txt and docs/database-table-inventory.txt
   from server.js. The guide says these files ship with the release and that
   when the guide and the generated file disagree, the generated file is right.
   Run after any change to server.js:   node scripts/inventory.js
   The check script runs it in --verify mode and fails if the committed files
   are out of date, so the inventories cannot quietly fall behind the code. */
const fs = require('node:fs');
const path = require('node:path');
const ROOT = path.resolve(__dirname, '..');
const src = fs.readFileSync(path.join(ROOT, 'server.js'), 'utf8');
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));

const routes = [];
for (const m of src.matchAll(/^\s*route\('(GET|POST|PATCH|PUT|DELETE)',\s*\/\^(.*?)\$\/,/gm)) {
  routes.push({ method: m[1], path: m[2].replace(/\\\//g, '/').replace(/\\\./g, '.').replace(/[()]/g, '') });
}
const publicApi = [];
{
  const m = /const PUBLIC_API = \[([\s\S]*?)\];/.exec(src);
  if (m) for (const x of m[1].matchAll(/\['(GET|POST)',\s*\/\^(.*?)\$\/\]/g)) publicApi.push(`${x[1]} ${x[2].replace(/\\\//g, '/').replace(/\\\./g, '.').replace(/[()]/g, '')}`);
}
/* The tables come from a real database, not from reading the SQL: the server
   is booted once against an empty throwaway file (no demo seed), every
   migration runs, and sqlite_master plus PRAGMA table_info are read back.
   What the file says is what a fresh bookit.db actually contains. */
const { spawnSync } = require('node:child_process');
const os = require('node:os');
const { DatabaseSync } = require('node:sqlite');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'bookit-inventory-'));
const dbFile = path.join(tmp, 'bookit.db');
const boot = spawnSync(process.execPath, ['--no-warnings', '-e', `
  process.env.PORT = '0';
  const http = require('node:http');
  const listen = http.Server.prototype.listen;
  /* let the server finish its boot work, then leave before it serves anything */
  http.Server.prototype.listen = function () { setImmediate(() => process.exit(0)); return this; };
  require(${JSON.stringify(path.join(ROOT, 'server.js'))});
`], { cwd: ROOT, env: { ...process.env, DB_PATH: dbFile, DOCS_DIR: path.join(tmp, 'docs'), PHOTOS_DIR: path.join(tmp, 'photos'), SECRET_FILE: path.join(tmp, '.secret'), SEED_DEMO: 'off', NODE_ENV: '' }, encoding: 'utf8', timeout: 60000 });
if (boot.status !== 0 || !fs.existsSync(dbFile)) {
  console.error('could not boot server.js against a throwaway database:\n' + (boot.stderr || boot.stdout));
  process.exit(1);
}
const tables = [];
{
  const db = new DatabaseSync(dbFile, { readOnly: true });
  for (const t of db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all()) {
    const cols = db.prepare(`PRAGMA table_info("${t.name.replace(/"/g, '""')}")`).all().map(c => `${c.name} ${c.type || ''}`.trim() + (c.pk ? ' PK' : '') + (c.notnull ? ' NOT NULL' : ''));
    tables.push({ name: t.name, cols });
  }
  db.close();
  try { fs.rmSync(tmp, { recursive: true, force: true }); } catch {}
}
tables.sort((a, b) => a.name.localeCompare(b.name));
routes.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));

const head = `# Generated by scripts/inventory.js from server.js — BookIt v${pkg.version}. Do not edit by hand.\n`;
const routeDoc = head + `# ${routes.length} routes registered through route(). Method, then pattern (regular expression, without the ^ and $).\n`
  + `# Everything under /api/admin/ requires an admin session and everything else a signed-in session,\n`
  + `# enforced in the dispatcher before the handler runs, except the ${publicApi.length} public routes marked *.\n\n`
  + routes.map(r => `${publicApi.includes(`${r.method} ${r.path}`) ? '*' : ' '} ${r.method.padEnd(6)} ${r.path}`).join('\n') + '\n'
  + `\n# Handled before the route table: GET /api/version, GET /api/health/live, GET /api/health/ready, POST /api/stripe/webhook,\n# GET /verify-email, GET /cover, GET /service-agreement, GET /privacy-consent, GET /templates, GET /sitemap.xml, GET /robots.txt.\n`;
const tableDoc = head + `# ${tables.length} tables, read back with PRAGMA table_info from a database the server created and migrated at boot.\n# Column, then declared type; PK marks the primary key. Order is the order in the file.\n\n`
  + tables.map(t => `${t.name} (${t.cols.length} columns)\n  ${t.cols.join(', ')}\n`).join('\n');

const outDir = path.join(ROOT, 'docs');
const targets = { 'api-route-inventory.txt': routeDoc, 'database-table-inventory.txt': tableDoc };
if (process.argv.includes('--verify')) {
  let stale = 0;
  for (const [name, body] of Object.entries(targets)) {
    let current = ''; try { current = fs.readFileSync(path.join(outDir, name), 'utf8'); } catch {}
    if (current !== body) { console.error(`docs/${name} is out of date — run: node scripts/inventory.js`); stale++; }
  }
  process.exit(stale ? 1 : 0);
}
fs.mkdirSync(outDir, { recursive: true });
for (const [name, body] of Object.entries(targets)) fs.writeFileSync(path.join(outDir, name), body);
console.log(`docs/api-route-inventory.txt: ${routes.length} routes · docs/database-table-inventory.txt: ${tables.length} tables`);
