#!/usr/bin/env node
'use strict';
/* BookIt — generate docs/api-route-inventory.txt and docs/database-table-inventory.txt
   from server.js. The guide says these files ship with the release and that
   when the guide and the generated file disagree, the generated file is right.
   Run after any change to server.js:   node scripts/inventory.js
   The check script runs it in --verify mode and fails if the committed files
   are out of date, so the inventories cannot quietly fall behind the code. */
const fs = require('node:fs');
const path = require('node:path');
const ROOT = path.resolve(__dirname, '..');
const src = fs.readFileSync(path.join(ROOT, 'server.js'), 'utf8');
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));

const routes = [];
for (const m of src.matchAll(/^\s*route\('(GET|POST|PATCH|PUT|DELETE)',\s*\/\^(.*?)\$\/,/gm)) {
  routes.push({ method: m[1], path: m[2].replace(/\\\//g, '/').replace(/\\\./g, '.').replace(/[()]/g, '') });
}
const publicApi = [];
{
  const m = /const PUBLIC_API = \[([\s\S]*?)\];/.exec(src);
  if (m) for (const x of m[1].matchAll(/\['(GET|POST)',\s*\/\^(.*?)\$\/\]/g)) publicApi.push(`${x[1]} ${x[2].replace(/\\\//g, '/').replace(/\\\./g, '.').replace(/[()]/g, '')}`);
}
const tables = [];
for (const m of src.matchAll(/CREATE TABLE IF NOT EXISTS (\w+)\s*\(([\s\S]*?)\);/g)) {
  const cols = m[2].split('\n').map(l => l.trim()).filter(l => l && !/^(PRIMARY|UNIQUE|FOREIGN|CHECK|CONSTRAINT)\b/i.test(l)).map(l => l.split(/\s+/)[0].replace(/,$/, ''));
  if (!tables.some(t => t.name === m[1])) tables.push({ name: m[1], cols });
}
for (const m of src.matchAll(/ALTER TABLE (\w+) ADD COLUMN (\w+)/g)) {
  const t = tables.find(x => x.name === m[1]);
  if (t && !t.cols.includes(m[2])) t.cols.push(m[2]);
}
for (const m of src.matchAll(/runLegacyAlter\(db, `ALTER TABLE (\w+) ADD COLUMN \$\{col\}`\)/g)) { /* column lists in loops are recorded from the loop arrays below */ }
for (const m of src.matchAll(/for \(const col of \[([^\]]+)\]\) \{\s*BOOKIT_MIGRATIONS\.runLegacyAlter\(db, `ALTER TABLE (\w+) ADD COLUMN \$\{col\}`\)/g)) {
  const t = tables.find(x => x.name === m[2]);
  if (!t) continue;
  for (const c of m[1].matchAll(/'([A-Za-z_]+)\b/g)) if (!t.cols.includes(c[1])) t.cols.push(c[1]);
}
tables.sort((a, b) => a.name.localeCompare(b.name));
routes.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));

const head = `# Generated by scripts/inventory.js from server.js — BookIt v${pkg.version}. Do not edit by hand.\n`;
const routeDoc = head + `# ${routes.length} routes registered through route(). Method, then pattern (regular expression, without the ^ and $).\n`
  + `# Everything under /api/admin/ requires an admin session and everything else a signed-in session,\n`
  + `# enforced in the dispatcher before the handler runs, except the ${publicApi.length} public routes marked *.\n\n`
  + routes.map(r => `${publicApi.includes(`${r.method} ${r.path}`) ? '*' : ' '} ${r.method.padEnd(6)} ${r.path}`).join('\n') + '\n'
  + `\n# Handled before the route table: GET /api/version, GET /api/health/live, GET /api/health/ready, POST /api/stripe/webhook,\n# GET /verify-email, GET /cover, GET /service-agreement, GET /privacy-consent, GET /templates, GET /sitemap.xml, GET /robots.txt.\n`;
const tableDoc = head + `# ${tables.length} persistent tables (CREATE TABLE IF NOT EXISTS, plus columns added by ALTER TABLE at boot).\n\n`
  + tables.map(t => `${t.name} (${t.cols.length} columns)\n  ${t.cols.join(', ')}\n`).join('\n');

const outDir = path.join(ROOT, 'docs');
const targets = { 'api-route-inventory.txt': routeDoc, 'database-table-inventory.txt': tableDoc };
if (process.argv.includes('--verify')) {
  let stale = 0;
  for (const [name, body] of Object.entries(targets)) {
    let current = ''; try { current = fs.readFileSync(path.join(outDir, name), 'utf8'); } catch {}
    if (current !== body) { console.error(`docs/${name} is out of date — run: node scripts/inventory.js`); stale++; }
  }
  process.exit(stale ? 1 : 0);
}
fs.mkdirSync(outDir, { recursive: true });
for (const [name, body] of Object.entries(targets)) fs.writeFileSync(path.join(outDir, name), body);
console.log(`docs/api-route-inventory.txt: ${routes.length} routes · docs/database-table-inventory.txt: ${tables.length} tables`);
