#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path');
const ROOT=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const pkg=JSON.parse(read('package.json')),meta=JSON.parse(read('docs/release-metadata.json'));
const routes=/# (\d+) routes/.exec(read('docs/api-route-inventory.txt'))?.[1];
const tables=/# (\d+) tables/.exec(read('docs/database-table-inventory.txt'))?.[1];
const schema=/SCHEMA_VERSION\s*:\s*Number\(process.env.SCHEMA_VERSION\s*\|\|\s*(\d+)/.exec(read('lib/version.js'))?.[1];
const lock=JSON.parse(read('package-lock.json'));
if(!routes||!tables||!schema||meta.version!==pkg.version||lock.version!==pkg.version||lock.packages[''].version!==pkg.version||meta.package_type!=='full source archive'||!/^[a-f0-9]{64}$/.test(meta.base_archive_sha256))throw Error('Release identity or generated inventories disagree.');
const handover=`THE CARE WEB — START HERE
=========================
Current release: v${pkg.version}
Default schema identifier: ${schema}
Registered routes: ${routes}
Database tables after boot: ${tables}

Generated by scripts/release-docs.js.

PACKAGE
${meta.output_archive} is a FULL SOURCE archive, including existing media,
artwork, fonts and vendor assets. Its enclosing folder is bookit-app-main.
Base supplied by the user: ${meta.base_archive} (v${meta.base_version})
Base SHA-256: ${meta.base_archive_sha256}
Remote GitHub HEAD and the deployed site were not accessed or changed.

IMPORTANT BEHAVIOUR CHANGE
Shared registers now start with office-only access. Existing entries and
historical versions are preserved. The office opens a register under /policies,
chooses Manage access to this register, sets its participant scope if appropriate,
and grants an approved worker read, append or edit access with an expiry.
A grant exposes that whole register: keep different participants in separate
registers. Participant-scoped grants also require current participant access.
Changing scope revokes previous worker grants; it never relabels existing rows.

INSTALL / UPDATE
1. Back up the deployed database, documents, photos and configuration using the
   existing authorised backup process. Keep the previous source for rollback.
2. Extract the ZIP. Work with the CONTENTS of bookit-app-main at the repository
   root; do not upload an enclosing folder inside the existing project.
3. Compare any newer repository changes before replacing source. Include all
   source/configuration files from this package, including the CI workflow.
4. Runtime databases, uploaded documents/photos, secrets and node_modules are
   intentionally excluded. PRESERVE them on the server. If old demo database
   files are still tracked in git, remove them from version control only;
   do not delete the deployed runtime database or uploaded files.
5. Use the repository's declared Node runtime, then run:
      npm ci --ignore-scripts
      npm run check
   See docs/TEST-RESULTS.md for the runtime actually tested and remaining limits.
6. Deploy using your existing process. On boot, three additive tables are created
   for cover reviews and register grants/scope. No existing records are deleted.
   Confirm /api/version reports ${pkg.version} and schema ${schema}; update an
   explicit SCHEMA_VERSION environment override if your host uses one.
7. In staging, test participant booking, worker cover with plan review, scoped
   register grants, concurrent register edits and native mobile/keyboard flows.
   Verify live provider integrations with authorised test accounts.

RECOVERY
Keep a pre-update backup. An older binary has broader register access; rolling
back application source can reintroduce the privacy and workflow defects.
Restore a tested backup and source together only through your normal recovery
process, with the effect on new records considered before restoration.

READ NEXT
docs/RELEASE-NOTES.md — changes, operation and remaining checks
docs/IMPLEMENTATION-MATRIX.md — every reported issue and its resolution
docs/TEST-RESULTS.md — executed commands and results
RELEASE-FILES.json — complete payload file hashes (excluding itself)
docs/history/ — historical receipts, not current deployment instructions
`;
const readme=`The Care Web v${pkg.version} — complete source package.

Extract ${meta.output_archive}; use the contents of bookit-app-main at the
repository root. Read STARTHERE.txt before updating. Preserve live runtime data.
This release adds scoped register access; the office must grant worker access.

Install/check: npm ci --ignore-scripts && npm run check
Refresh generated documents: npm run release:docs

See docs/RELEASE-NOTES.md, docs/IMPLEMENTATION-MATRIX.md and docs/TEST-RESULTS.md.
The package has not been pushed to GitHub or deployed to the live site.
`;
let stale=0;for(const [name,content]of Object.entries({'STARTHERE.txt':handover,'readme.txt':readme})){
 if(process.argv.includes('--verify')){if(read(name)!==content){console.error(name+' is stale: run npm run release:docs');stale++;}}
 else fs.writeFileSync(path.join(ROOT,name),content);
}
if(!process.argv.includes('--verify'))console.log(`Release docs: v${pkg.version}, schema ${schema}, ${routes} routes, ${tables} tables`);
process.exitCode=stale?1:0;
