#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path');
const ROOT=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const pkg=JSON.parse(read('package.json')),meta=JSON.parse(read('docs/release-metadata.json'));
const routes=/# (\d+) routes/.exec(read('docs/api-route-inventory.txt'))?.[1];
const tables=/# (\d+) tables/.exec(read('docs/database-table-inventory.txt'))?.[1];
const schema=/SCHEMA_VERSION\s*:\s*Number\(process.env.SCHEMA_VERSION\s*\|\|\s*(\d+)/.exec(read('lib/version.js'))?.[1];
const lock=JSON.parse(read('package-lock.json'));
if(!routes||!tables||!schema||meta.version!==pkg.version||lock.version!==pkg.version||lock.packages[''].version!==pkg.version||meta.package_type!=='full source archive'||!/^[a-f0-9]{64}$/.test(meta.base_archive_sha256))throw Error('Release identity or generated inventories disagree.');
const handover=`THE CARE WEB — START HERE
=========================
Current release: v${pkg.version}
Default schema identifier: ${schema}
Registered routes: ${routes}
Database tables after boot: ${tables}

Generated by scripts/release-docs.js.

PACKAGE
This is the complete installed source tree for v${pkg.version}.
A changed-files update ZIP contains only the differences from its stated base;
follow its UPDATE-INSTRUCTIONS.txt and merge into your existing source tree.
Do not replace the existing repository with a partial update ZIP.
Base source release: v${meta.base_version}
Base package reference: ${meta.base_archive}
Base SHA-256: ${meta.base_archive_sha256}
Source baseline commit: ${meta.base_commit}
The deployed site has not been changed or verified by this source release.

AUTOMATIC BILLING AND COMPLETE BLOCK REGISTER
NSW holiday detection and saved fallback calendars run automatically.
New self-managed/private worker submissions queue a separate invoice and PDF
email immediately. Explicit participant review opens payment in the same journey.
Plan-managed/NDIA work retains approval-first routing. Recovery runs in the
background, including existing approved unissued visits after restart.
No blanket finance-review, holiday-review or private-ready approval is required.
Time/date rate boundaries are itemised before approval. Issued snapshots and
previously approved amounts are preserved. Explicit holds and disputed timesheets
remain deliberate stops. Invoice mail retries automatically with visible status.
Email transport must be configured; queued does not mean sent or paid.
The complete source register is docs/block-register/index.html, with CSV/JSON and
all conditional branches. docs/BLOCKS-AND-AUTOMATION.md explains remaining decisions.
See docs/CHANGELOG-v88.4.5.md and docs/USER-GUIDE.html.

BOOKING EMAILS
Admin > Settings > Email setup shows the configured sender and a test to your
own account. Today > Email delivery shows message subjects and recipient/status
evidence. Participant booking receipts, authorised helper updates and recurring
changes use the durable queue. Provider acceptance is not inbox confirmation.
See docs/EMAIL-SETUP-v88.4.5.md for diagnosis on this existing website.

LAUNCH CHECKS AND OVERNIGHT SUPPORT
Launch checks groups six practical areas, automatic monitoring and optional
research, with all original findings retained in Audit history. No all-approved
launch gate is introduced. Inactive overnight bookings show a flat nightly quote
and included active support; hourly support shows the date/time breakdown.
Signed price keys protect the displayed estimate before a request is saved.
Additional sleepover support uses actual date/time rates. Legacy invalid
arrangements preserve recorded work and require charge correction before issue.

ADMIN WORKSPACE
One shared navigation: Today, People, Bookings, Money, Records, Reports, Settings.
Search admin tools by task; each destination loads only its own required data.
Invoices, receipts, claims, payroll and payment connections have separate pages.
Long records have scoped search and pagination. Existing permissions, financial
actions and evidence requirements remain enforced. Account settings stay separate.
See docs/ADMIN-NAVIGATION-v88.4.2.md.

ADDRESSES AND VISIT LOCATIONS
Participants can save private address and arrival details in Settings. Bookings
keep independent location snapshots, with saved/other/community/confirm-later
choices. Assigned workers see the area before acceptance and exact meeting
details after acceptance. Explicit changes queue generic notices and a worker
review task without changing the booking status. No new billing gate is added.
Worker profiles show their declared service areas; no live location is tracked.
See docs/LOCATION-PRIVACY-v88.4.1.md and the updated USER-GUIDE.html.

PAYMENT TRACKING
Invoices link to a protected payment page. Provider confirmations update balances
with duplicate protection, partial payments, receipts and overdue reminders.
New customer payments must use the invoice link. Stripe checkout supports cards
and optionally enabled PayTo. Zai setup and ordinary bank-transfer instructions
are removed. Existing payment evidence and unallocated historical receipts remain
available to the office. Queued invoice PDFs and demands are refreshed before
sending; previously delivered copies cannot be recalled.
Configure Stripe using docs/PAYMENT-SETUP-v88.4.0.md. These integrations
do not confirm onward business-bank settlement or transfer wages. Worker pay
notices clearly identify external payment results recorded by the office.

INVOICE WITHDRAWAL
Withdraw invoice confirms and submits correctly. Each invoice has one Record
payment action. Withdrawal keeps its snapshot and history, cancels queued demand
mail, queues notice to the original payer and holds its shifts until released.
Reissue uses a fresh invoice number. Retired card links close with durable retries.
Partial payments show the remaining balance; paid invoices require payment review
before withdrawal. NDIA claims appear separately from participant invoices.

CLEAR TASKS
Office actions, Waiting on people and Website checks have separate views.
Every row shows responsibility, status and next step; buttons name the action.
Red: urgent/overdue. Amber: action required. Blue: waiting. Labels accompany colour.
Website HTTPS certificates are checked automatically from APP_URL. Healthy checks
clear alerts; connection failures retry hourly. Hosting handles certificate renewal.
See docs/task-clarity-preview.html for interactive fictional examples.

NAVIGATION AND WEBSITE USABILITY
The header shows three or four primary tasks for the signed-in role.
The worker account menu has eight actions, including Refer a friend.
Bookings opens a month/week calendar for workers and participants. The List
switch keeps existing booking controls. Select a day, then Open booking.
A small red request count appears beside Bookings and on the mobile menu for
workers with future unanswered requests. It updates while the site is open.
Calendar queries use the visible date range and carry overnight visits across
midnight; each booking opens its own scoped record even beyond the old list cap.
The date grid fits its column; the selected-day panel moves below it on narrow layouts.
See docs/booking-calendar-preview.html for fictional examples.
Messages remain in the header. Referrals lead to the existing worker referral page.
Credentials has an essential-document checklist and the complete document dropdown.
Each uploaded file has View, Replace and Remove or Request removal actions.
Credentials uses green for verified, blue for pending office review and amber
for missing files. Text and icons accompany colour. View document status jumps
straight to the checklist, and verified files show the recorded review date.
See docs/credential-status-preview.html for synthetic examples.
Verified originals remain on record; replacements are submitted for office review.
Next actions groups related steps into a short, prioritised list.
The first three groups are shown; overdue and today groups remain visible.
Office reviews and secondary tools are collapsed. Buttons describe the next step.
The office task queue uses compact rows with assignment forms behind Details.
Personal Settings are linked rather than duplicated.
A synthetic interactive preview is in docs/next-actions-preview.html.
Emergency contacts are in Profile; digest, quiet hours and calendar in Notifications.
Coordinators retain scoped tools for their selected participant.
Navigation starts at the top; delayed background callbacks cannot scroll other pages.
Review docs/SITE-USABILITY-REVIEW.md for page coverage and browser limits.
Worker Settings retains its independent loading state and failure retry.
Open Settings to manage availability, credentials, earnings, training and security.
Open Admin > Verification > Worker documents for grouped uploaded evidence.
HTML agreements and support plans open in an isolated read-only preview.
PDF files use compact page and zoom controls; rotation and page text are in More.
Retry appears only on failure; downloads remain available.
Platform-issued module records are shown under Training.
Details-only records explicitly identify that no file has been uploaded.
Choose available reviewers in Automation settings to enable automatic assignment.
Approve a combined checklist to start its bounded, state-aware follow-ups.
This package retains all 26 process improvements J01–J26 from v88.2.0.
Open Next actions after signing in. Office users also have task ownership,
recruitment, pay batches, message delivery, invoice exceptions and setup panels.
The earlier scoped register permissions remain in force.

CONFIGURATION BEFORE USE
- Open Admin > Launch & operations for all 44 finding/acceptance records.
- Check approval-to-invoice and email delivery on your existing prelaunch website; NSW holidays are automatic. Confirm actual business tax/agreement and payroll settings. No A09 or holiday-review gate applies to routine invoice issue.
- Every payroll line needs reviewed wages, super, allowances and a calculation reference; a different
  approver signs the batch. Booking allocation exports are estimates.
- Review migrated incident awareness and separate notification/five-day/final-report obligations.
- Read docs/LAUNCH-ACCEPTANCE.md and docs/USER-GUIDE.html before launch.
- Confirm private billing arrangements and tax treatment in Next actions > Setup.
- Confirm the first externally unprocessed payroll date before enabling daily
  draft preparation. Exporting a batch does not mark anyone paid.
- Configure and test the existing email transport; check the delivery queue.
- Document assistance is off until approved and the existing AI provider,
  model, processing region and consent requirements are configured.
- Calendar subscriptions are optional and require the person's confirmation.

INSTALL / UPDATE
1. Back up the deployed database, documents, photos and configuration using the
   existing authorised backup process. Keep the previous source for rollback.
2. Extract the changed-files ZIP and merge its files at the repository root.
   Do not upload an enclosing folder inside the existing project.
3. Compare any newer repository changes before replacing source. Include all
   source/configuration files from this package, including the CI workflow.
4. Runtime databases, uploaded documents/photos, secrets and node_modules are
   intentionally excluded. PRESERVE them on the server. If old demo database
   files are still tracked in git, remove them from version control only;
   do not delete the deployed runtime database or uploaded files.
5. Use the repository's declared Node runtime, then run:
      npm ci --ignore-scripts
      npm run check
   See docs/TEST-RESULTS.md for the runtime actually tested and remaining limits.
6. Update the existing prelaunch website. No second website is required.
   This release retains the current schema and historical payment evidence.
   This upgrade does not reinterpret unknown funding.
   Confirm /api/version reports ${pkg.version} and schema ${schema}; update an
   explicit SCHEMA_VERSION environment override if your host uses one.
7. On your existing prelaunch website, check participant and helper setup, concurrent plan saves, worker
   recruitment, series acceptance, leave/cover, notes and travel, approvals,
   invoice reconciliation, payroll batches, calendar changes and recovery.
   Check mobile, keyboard and screen-reader use. Verify configured integrations
   with authorised provider events and the payment checks in the setup guide.

RECOVERY
Keep a pre-update backup. An older binary has broader register access; rolling
back application source can reintroduce the privacy and workflow defects.
Restore a tested backup and source together only through your normal recovery
process, with the effect on new records considered before restoration.

READ NEXT
docs/RELEASE-NOTES.md — changes, operation and remaining checks
docs/IMPLEMENTATION-MATRIX.md — J01–J26 delivery and validation map
docs/WORKFLOW-OPERATIONS.md — existing workflow configuration and automation
docs/ADMIN-VERIFICATION.md — the new review workspace
docs/admin-verification-preview.html — standalone sample design preview
docs/TEST-RESULTS.md — executed commands and results
RELEASE-FILES.json — complete payload file hashes (excluding itself)
docs/history/ — historical receipts, not current deployment instructions
`;
const readme=`The Care Web v${pkg.version} — complete source package.

Extract ${meta.output_archive}; merge its files at the repository root. Read STARTHERE.txt before updating. Preserve live runtime data.
This release implements launch-audit source corrections and updates the full user guide.
NSW holidays and ordinary invoicing are automatic. Independently reviewed payroll
components remain required; preparing/exporting payroll does not transfer wages.
PDF/HTML previews and earlier verification automations are retained.
Configure private billing,
email, payroll cutover and any optional document assistance before use.

Install/check: npm ci --ignore-scripts && npm run check
Refresh generated documents: npm run release:docs

See docs/RELEASE-NOTES.md, docs/IMPLEMENTATION-MATRIX.md and docs/TEST-RESULTS.md.
The package is a reviewable source update. Live deployment/provider activation
remains separate. See docs/PAYMENT-SETUP-v88.4.0.md.
`;
let stale=0;for(const [name,content]of Object.entries({'STARTHERE.txt':handover,'readme.txt':readme})){
 if(process.argv.includes('--verify')){if(read(name)!==content){console.error(name+' is stale: run npm run release:docs');stale++;}}
 else fs.writeFileSync(path.join(ROOT,name),content);
}
if(!process.argv.includes('--verify'))console.log(`Release docs: v${pkg.version}, schema ${schema}, ${routes} routes, ${tables} tables`);
process.exitCode=stale?1:0;
