#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path');
const ROOT=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');
const pkg=JSON.parse(read('package.json')),meta=JSON.parse(read('docs/release-metadata.json'));
const routes=/# (\d+) routes/.exec(read('docs/api-route-inventory.txt'))?.[1];
const tables=/# (\d+) tables/.exec(read('docs/database-table-inventory.txt'))?.[1];
const schema=/SCHEMA_VERSION\s*:\s*Number\(process.env.SCHEMA_VERSION\s*\|\|\s*(\d+)/.exec(read('lib/version.js'))?.[1];
const lock=JSON.parse(read('package-lock.json'));
if(!routes||!tables||!schema||meta.version!==pkg.version||lock.version!==pkg.version||lock.packages[''].version!==pkg.version||meta.package_type!=='full source archive'||!/^[a-f0-9]{64}$/.test(meta.base_archive_sha256))throw Error('Release identity or generated inventories disagree.');
const handover=`THE CARE WEB — START HERE
=========================
Current release: v${pkg.version}
Default schema identifier: ${schema}
Registered routes: ${routes}
Database tables after boot: ${tables}

Generated by scripts/release-docs.js.

PACKAGE
${meta.output_archive} is a FULL SOURCE archive, including existing media,
artwork, fonts and vendor assets. Its enclosing folder is bookit-app-main.
Base supplied by the user: ${meta.base_archive} (v${meta.base_version})
Base SHA-256: ${meta.base_archive_sha256}
Remote GitHub HEAD and the deployed site were not accessed or changed.

NAVIGATION AND WEBSITE USABILITY
The header shows three or four primary tasks for the signed-in role.
The account menu has five to seven actions. Messages remain in the header.
Credentials > Add or replace files opens the dedicated document uploader.
Review docs/SITE-USABILITY-REVIEW.md for page coverage and browser limits.
Worker Settings retains its independent loading state and failure retry.
Open Settings to manage availability, credentials, earnings, training and security.
Open Admin > Verification > Worker documents for grouped uploaded evidence.
HTML agreements and support plans open in an isolated read-only preview.
PDF files use compact page and zoom controls; rotation and page text are in More.
Retry appears only on failure; downloads remain available.
Platform-issued module records are shown under Training.
Details-only records explicitly identify that no file has been uploaded.
Choose available reviewers in Automation settings to enable automatic assignment.
Approve a combined checklist to start its bounded, state-aware follow-ups.
This package retains all 26 process improvements J01–J26 from v88.2.0.
Open Next actions after signing in. Office users also have task ownership,
recruitment, pay batches, message delivery, invoice exceptions and setup panels.
The earlier scoped register permissions remain in force.

CONFIGURATION BEFORE USE
- Confirm private billing arrangements and tax treatment in Next actions > Setup.
- Confirm the first externally unprocessed payroll date before enabling daily
  draft preparation. Exporting a batch does not mark anyone paid.
- Configure and test the existing email transport; check the delivery queue.
- Document assistance is off until approved and the existing AI provider,
  model, processing region and consent requirements are configured.
- Calendar subscriptions are optional and require the person's confirmation.

INSTALL / UPDATE
1. Back up the deployed database, documents, photos and configuration using the
   existing authorised backup process. Keep the previous source for rollback.
2. Extract the ZIP. Work with the CONTENTS of bookit-app-main at the repository
   root; do not upload an enclosing folder inside the existing project.
3. Compare any newer repository changes before replacing source. Include all
   source/configuration files from this package, including the CI workflow.
4. Runtime databases, uploaded documents/photos, secrets and node_modules are
   intentionally excluded. PRESERVE them on the server. If old demo database
   files are still tracked in git, remove them from version control only;
   do not delete the deployed runtime database or uploaded files.
5. Use the repository's declared Node runtime, then run:
      npm ci --ignore-scripts
      npm run check
   See docs/TEST-RESULTS.md for the runtime actually tested and remaining limits.
6. Deploy using your existing process. No schema change is needed from v88.2.6. Earlier additive
   migrations still run when upgrading an older release.
   Existing records are retained. This upgrade does not reinterpret unknown funding.
   Confirm /api/version reports ${pkg.version} and schema ${schema}; update an
   explicit SCHEMA_VERSION environment override if your host uses one.
7. In staging, test participant and helper setup, concurrent plan saves, worker
   recruitment, series acceptance, leave/cover, notes and travel, approvals,
   invoice reconciliation, payroll batches, calendar changes and recovery.
   Check mobile, keyboard and screen-reader use. Verify configured integrations
   with authorised provider test accounts before production use.

RECOVERY
Keep a pre-update backup. An older binary has broader register access; rolling
back application source can reintroduce the privacy and workflow defects.
Restore a tested backup and source together only through your normal recovery
process, with the effect on new records considered before restoration.

READ NEXT
docs/RELEASE-NOTES.md — changes, operation and remaining checks
docs/IMPLEMENTATION-MATRIX.md — J01–J26 delivery and validation map
docs/WORKFLOW-OPERATIONS.md — existing workflow configuration and automation
docs/ADMIN-VERIFICATION.md — the new review workspace
docs/admin-verification-preview.html — standalone sample design preview
docs/TEST-RESULTS.md — executed commands and results
RELEASE-FILES.json — complete payload file hashes (excluding itself)
docs/history/ — historical receipts, not current deployment instructions
`;
const readme=`The Care Web v${pkg.version} — complete source package.

Extract ${meta.output_archive}; use the contents of bookit-app-main at the
repository root. Read STARTHERE.txt before updating. Preserve live runtime data.
This release simplifies navigation and fixes credential-upload navigation.
PDF/HTML previews and earlier verification automations are retained.
Configure private billing,
email, payroll cutover and any optional document assistance before use.

Install/check: npm ci --ignore-scripts && npm run check
Refresh generated documents: npm run release:docs

See docs/RELEASE-NOTES.md, docs/IMPLEMENTATION-MATRIX.md and docs/TEST-RESULTS.md.
The package has not been pushed to GitHub or deployed to the live site.
`;
let stale=0;for(const [name,content]of Object.entries({'STARTHERE.txt':handover,'readme.txt':readme})){
 if(process.argv.includes('--verify')){if(read(name)!==content){console.error(name+' is stale: run npm run release:docs');stale++;}}
 else fs.writeFileSync(path.join(ROOT,name),content);
}
if(!process.argv.includes('--verify'))console.log(`Release docs: v${pkg.version}, schema ${schema}, ${routes} routes, ${tables} tables`);
process.exitCode=stale?1:0;
